# Generated by Django 5.0.1 on 2026-03-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn sử dụng'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
    ]
