# Generated by Django 5.0.1 on 2026-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_coupon_valid_to_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
    ]
